- name: example ec2 group
  ec2_group:
    name: mysec
    description: an example EC2 group
    vpc_id: vpc-ceff7ba9
    region: us-west-2
    aws_access_key: AKIAIGMS7HAAXTK4Z77A
    aws_secret_key: E1pPx83Xlw83c9uL0wCoxwElzY/uTDBJRaren+dY
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 443
        to_port: 443
      - proto: tcp
        from_port: 3306
        to_port: 3306
      - proto: udp
        from_port: 10050
        to_port: 10050
        cidr_ip: 10.0.0.0/8
      - proto: udp
        from_port: 10051
        to_port: 10051
      - proto: icmp
        from_port: 8 # icmp type, -1 = any type
        to_port:  -1 # icmp subtype, -1 = any subtype
        cidr_ip: 10.0.0.0/8
      - proto: all
        # the containing group name may be specified here
        #group_name: karthi
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
        #group_name: karthi
        # description to use if example-other needs to be created
        group_desc: other example EC2 group
